### ISSUE TITLE
Can you help on how to use this with Theano or Keras?

### ISSUE THREAD

**Issue by foo123** [ameybarapatre/WaveletNeuralNetwork#4]
Hello can you provide some information on how to use this with Theano or even Keras library?
I want to use wavelet neural networks for a project i work on and this might be useful. One the other hand maybe you can provide links to other libraries.

Thank you,
Nikos

**Comment by ameybarapatre** [comment]
This is a theano implementation so it should ideally work if you have theano but I'm not sure if it uses some  
depreciated code since I coded this a while back. As for the keras implementations I suggest  you look at the way dimension broadcasting is done in this code to calculate the waveleon output and replicate it in keras.

**Comment by foo123** [comment]
So the code might be out of date for Theano, this is what i understand. Can you elaborate a little more on Keras. What do you mean "how broadcasting is done"? I am new with both Theano and Keras and any help is greatly appreciated.

Cheers

**Comment by ameybarapatre** [comment]
https://learningtensorflow.com/broadcasting/   Might help understand dimension broadcasting  for Tensorflow  the same goes for Theano http://deeplearning.net/software/theano/tutorial/broadcasting.html

I am not sure of the implementation details for the same in Keras but since it uses one of these backends it is feasible.
